-- Initial PostgreSQL schema for the future hosted database.
-- Runtime code still uses local SQLite until the adapter migration is verified.

create table if not exists jobs (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text not null,
  company text not null default '',
  title text not null default '',
  job_type text not null default '',
  published_at text not null default '',
  deadline text not null default '',
  recruiting_numbers text not null default '',
  detail_url text not null default '',
  first_seen_at text not null,
  last_seen_at text not null,
  review_status text not null default 'pending',
  dedupe_key text not null default '',
  location_checked_at text not null default '',
  unique (source, source_id)
);

create table if not exists job_locations (
  job_id bigint not null references jobs(id) on delete cascade,
  location text not null,
  primary key (job_id, location)
);

create table if not exists job_industries (
  job_id bigint not null references jobs(id) on delete cascade,
  industry text not null,
  primary key (job_id, industry)
);

create table if not exists source_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  started_at text not null,
  finished_at text,
  status text not null,
  fetched_count integer not null default 0,
  new_count integer not null default 0,
  error text
);

create table if not exists source_status (
  source text primary key,
  last_started_at text,
  last_finished_at text,
  last_status text not null default 'never',
  last_success_at text,
  last_failure_at text,
  last_error text,
  fetched_count integer not null default 0,
  new_count integer not null default 0
);

create table if not exists review_events (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text not null,
  old_status text not null,
  new_status text not null,
  actor text not null,
  created_at text not null
);

create table if not exists admin_auth_limits (
  id integer primary key check (id = 1),
  window_started_at bigint not null,
  failures integer not null
);

create index if not exists idx_jobs_published on jobs (published_at);
create index if not exists idx_jobs_dedupe on jobs (dedupe_key);
create index if not exists idx_runs_source on source_runs (source, id);
create index if not exists idx_review_events_id on review_events (id);
create index if not exists idx_job_locations_location on job_locations (location, job_id);
create index if not exists idx_job_industries_industry on job_industries (industry, job_id);

