-- Append-only source withdrawal history, owned by the website administrator.
create table if not exists source_controls (
  id bigint generated by default as identity primary key,
  source text not null,
  action text not null check (action in ('restrict', 'restore')),
  reason text not null check (reason in ('source_request', 'privacy', 'copyright', 'inaccurate', 'resolved')),
  actor text not null,
  created_at text not null
);
create index if not exists idx_source_controls_source on source_controls (source, id desc);
alter table source_controls enable row level security;
